apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"

spec:
  type: {{ .Values.backend.service.type }}

  selector:
    app: backend

  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}