apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.backend.containerPort }}

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DATABASE_URL

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.containerPort }}

            initialDelaySeconds: 3
            periodSeconds: 5