apiVersion: v1
kind: ConfigMap

metadata:
  name: postgres-init

data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS tasks (
        id SERIAL PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        completed BOOLEAN NOT NULL DEFAULT FALSE
    );

    INSERT INTO tasks (title, completed)
    SELECT 'Learn Go', false
    WHERE NOT EXISTS (
        SELECT 1
        FROM tasks
        WHERE title = 'Learn Go'
    );

    INSERT INTO tasks (title, completed)
    SELECT 'Learn Docker', false
    WHERE NOT EXISTS (
        SELECT 1
        FROM tasks
        WHERE title = 'Learn Docker'
    );

    INSERT INTO tasks (title, completed)
    SELECT 'Learn PostgreSQL', false
    WHERE NOT EXISTS (
        SELECT 1
        FROM tasks
        WHERE title = 'Learn PostgreSQL'
    );